# Generated by Django 5.1.6 on 2025-03-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('advice', models.CharField(max_length=255)),
            ],
        ),
    ]
